/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/imac.glb -t -o src/components/3d/IMac.tsx 
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/imac-2021-304cb06ffb554883a7a642b2b56754c1
Title: iMac 2021
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Screen_DarkBlue_0: THREE.Mesh
    Screen_LightBlue_0: THREE.Mesh
    Screen_Black_0: THREE.Mesh
    Screen_White_0: THREE.Mesh
    Screen_Screen_0: THREE.Mesh
    Screen_Chrome_0: THREE.Mesh
    Screen_CamBlack_0: THREE.Mesh
    Screen_Lens_0: THREE.Mesh
    Screen_Glass_0: THREE.Mesh
    Screen_Black001_0: THREE.Mesh
    Screen_Yellow_0: THREE.Mesh
    Rotate_Metal_0: THREE.Mesh
    Rotate_Metal2_0: THREE.Mesh
    Stand_LightBlue_0: THREE.Mesh
  }
  materials: {
    DarkBlue: THREE.MeshStandardMaterial
    LightBlue: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
    ['Cam.Black']: THREE.MeshStandardMaterial
    Lens: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Black.001']: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Metal2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/imac.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[0.032, 0, 0.387]}>
          <group position={[-0.03, 0, -0.387]}>
            <mesh geometry={nodes.Screen_DarkBlue_0.geometry} material={materials.DarkBlue} />
            <mesh geometry={nodes.Screen_LightBlue_0.geometry} material={materials.LightBlue} />
            <mesh geometry={nodes.Screen_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Screen_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.Screen_Screen_0.geometry} material={materials.Screen} />
            <mesh geometry={nodes.Screen_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Screen_CamBlack_0.geometry} material={materials['Cam.Black']} />
            <mesh geometry={nodes.Screen_Lens_0.geometry} material={materials.Lens} />
            <mesh geometry={nodes.Screen_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Screen_Black001_0.geometry} material={materials['Black.001']} />
            <mesh geometry={nodes.Screen_Yellow_0.geometry} material={materials.Yellow} />
          </group>
          <mesh geometry={nodes.Rotate_Metal_0.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Rotate_Metal2_0.geometry} material={materials.Metal2} />
        </group>
        <mesh geometry={nodes.Stand_LightBlue_0.geometry} material={materials.LightBlue} />
      </group>
    </group>
  )
}

useGLTF.preload('/imac.glb')
